name: Sync Upstream Releases

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      repositories:
        description: '要同步的仓库列表 (格式: owner/repo, 多个用逗号分隔)'
        required: true
        default: 'AlistGo/alist,immortalwrt/immortalwrt'

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TARGET_REPO: "${{ github.repository }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq git
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install -y gh

      - name: Determine repositories
        id: set-repos
        run: |
          if [ -n "${{ github.event.inputs.repositories }}" ]; then
            REPOSITORIES="${{ github.event.inputs.repositories }}"
          elif [ -n "${{ vars.UPSTREAM_REPOSITORIES }}" ]; then
            REPOSITORIES="${{ vars.UPSTREAM_REPOSITORIES }}"
          else
            REPOSITORIES="AlistGo/alist"
          fi
          echo "REPOSITORIES=${REPOSITORIES}" >> $GITHUB_OUTPUT

      - name: Process repositories
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          mkdir -p sync-history

          echo "${{ steps.set-repos.outputs.REPOSITORIES }}" | tr ',' '\n' | while read -r upstream_repo; do
            owner=$(cut -d/ -f1 <<< "$upstream_repo")
            repo_name=$(cut -d/ -f2 <<< "$upstream_repo")
            history_file="sync-history/${owner}_${repo_name}.txt"
            workdir=$(mktemp -d)
            trap 'rm -rf "$workdir"' EXIT

            # 尝试从Release获取
            release_response=$(curl -sL \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ github.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$upstream_repo/releases/latest")

            tag_name=$(jq -r '.tag_name' <<< "$release_response")
            zip_url=$(jq -r '.zipball_url' <<< "$release_response")

            # 判断来源类型
            if [[ "$tag_name" != "null" && "$zip_url" != "null" ]]; then
              echo "Using Release source: $tag_name"
              source_type="release"
              download_success=false
              
              # 重试下载逻辑（修复语法结构）
              for i in {1..3}; do
                if wget -q -O "$workdir/source.zip" "$zip_url"; then
                  unzip -q "$workdir/source.zip" -d "$workdir/source"
                  mv "$workdir"/source/*/* "$workdir/source_content"
                  download_success=true
                  break
                else
                  echo "Release download failed, attempt $i"
                  sleep 5
                fi  # 闭合if语句
              done   # 闭合for循环

              if ! $download_success; then
                echo "All release download attempts failed"
                continue
              fi
            else
              # 回退到Tags
              echo "No valid Release, fallback to Tags"
              tags_response=$(curl -sL \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ github.token }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/$upstream_repo/tags")
              
              tag_name=$(jq -r '.[0].name' <<< "$tags_response")
              [[ "$tag_name" == "null" ]] && continue
              source_type="tag"
              
              git clone --depth 1 --branch "$tag_name" "https://github.com/$upstream_repo.git" "$workdir/source"
              mv "$workdir/source" "$workdir/source_content"
            fi  # 闭合if-else语句

            # 打包发布逻辑
            pushd "$workdir/source_content" >/dev/null
            archive_name="${repo_name}-${tag_name//\//-}.zip"
            zip -qr "../$archive_name" .
            popd >/dev/null

            # 创建Release
            timestamp=$(date -u +"%Y-%m-%d-%s")
            sync_tag="release-${timestamp}"
            md5_sum=$(md5sum "$workdir/$archive_name" | awk '{ print $1 }')

            gh release create "$sync_tag" "$workdir/$archive_name" \
              --title "${timestamp}: ${repo_name} (${tag_name})" \
              --notes "MD5: ${md5_sum}\nRepo: ${upstream_repo}\nSource: ${source_type}\nTag: ${tag_name}"

            echo "$tag_name" > "$history_file"
          done  # 闭合while循环

      - name: Commit sync history
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sync-history
          git commit -m "Update sync records" || exit 0
          git push
