name: Sync Upstream Releases

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:
    inputs:
      repositories:
        description: '要同步的仓库列表 (格式: owner/repo, 多个用逗号分隔)'
        required: false

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许创建 Release
    env:
      TARGET_REPO: "${{ github.repository }}"  # ✅ 关键修改：目标仓库设为当前仓库

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          # 安装 gh CLI
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install -y gh

      - name: Determine repositories
        id: set-repos
        run: |
          if [ -n "${{ github.event.inputs.repositories }}" ]; then
            REPOSITORIES="${{ github.event.inputs.repositories }}"
          elif [ -n "${{ vars.UPSTREAM_REPOSITORIES }}" ]; then
            REPOSITORIES="${{ vars.UPSTREAM_REPOSITORIES }}"
          else
            REPOSITORIES="AlistGo/alist"  # 默认同步仓库
          fi
          echo "REPOSITORIES=${REPOSITORIES}" >> $GITHUB_OUTPUT

      - name: Process repositories
        env:
          GH_TOKEN: ${{ github.token }}  # ✅ 使用默认 Token
        run: |
          set -euo pipefail
          mkdir -p sync-history

          echo "${{ steps.set-repos.outputs.REPOSITORIES }}" | tr ',' '\n' | while read -r upstream_repo; do
            owner=$(cut -d/ -f1 <<< "$upstream_repo")
            repo_name=$(cut -d/ -f2 <<< "$upstream_repo")
            history_file="sync-history/${owner}_${repo_name}.txt"

            # 获取上游 Release 信息
            response=$(curl -sL \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ github.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$upstream_repo/releases/latest")

            tag_name=$(jq -r '.tag_name' <<< "$response")
            [[ "$tag_name" == "null" ]] && continue

            # 检查是否已同步
            last_synced=$(cat "$history_file" 2>/dev/null || echo "init")
            [[ "$tag_name" == "$last_synced" ]] && continue

            # 下载源码
            wget -q -O "${repo_name}-${tag_name}.zip" "$(jq -r '.zipball_url' <<< "$response")"

            # 计算MD5校验和
            md5_sum=$(md5sum "${repo_name}-${tag_name}.zip" | awk '{ print $1 }')

            # 生成同步时间戳 (UTC时间)
            sync_time=$(date -u +"%Y-%m-%d-%s")

            # 创建 Release（包含时间戳、仓库名、上游tag和MD5）
            gh release create "${tag_name}" "${repo_name}-${tag_name}.zip" \
              --title "${sync_time}: ${repo_name}  tag:${tag_name}" \
              --notes "${md5_sum} ${repo_name}"

            # 记录同步历史
            echo "$tag_name" > "$history_file"
            rm -f "${repo_name}-${tag_name}.zip"
          done

      - name: Commit sync history
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sync-history
          git commit -m "Update sync records" || exit 0
          git push
