name: Sync Upstream Releases

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      repositories:
        description: '要同步的仓库列表 (格式: owner/repo, 多个用逗号分隔)'
        required: true
        default: 'AlistGo/alist,AlistGo/alist-web,MHSanaei/3x-ui,XTLS/Xray-core,immortalwrt/immortalwrt'

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TARGET_REPO: "${{ github.repository }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq git
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install -y gh

      - name: Determine repositories
        id: set-repos
        run: |
          if [ -n "${{ github.event.inputs.repositories }}" ]; then
            REPOSITORIES="${{ github.event.inputs.repositories }}"
          elif [ -n "${{ vars.UPSTREAM_REPOSITORIES }}" ]; then
            REPOSITORIES="${{ vars.UPSTREAM_REPOSITORIES }}"
          else
            REPOSITORIES="AlistGo/alist"
          fi
          echo "REPOSITORIES=${REPOSITORIES}" >> $GITHUB_OUTPUT

      - name: Process repositories
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          mkdir -p sync-history

          echo "${{ steps.set-repos.outputs.REPOSITORIES }}" | tr ',' '\n' | while read -r upstream_repo; do
            owner=$(cut -d/ -f1 <<< "$upstream_repo")
            repo_name=$(cut -d/ -f2 <<< "$upstream_repo")
            history_file="sync-history/${owner}_${repo_name}.txt"

            # 获取最新有效标签（兼容无Release的情况）
            tag_name=$(curl -sL \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ github.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$upstream_repo/tags" | jq -r '.[0].name')

            [ -z "$tag_name" ] || [ "$tag_name" == "null" ] && continue

            # 检查是否已同步
            last_synced=$(cat "$history_file" 2>/dev/null || echo "init")
            [[ "$tag_name" == "$last_synced" ]] && continue

            # 创建临时工作目录
            workdir=$(mktemp -d)
            trap 'rm -rf "$workdir"' EXIT

            # 克隆仓库并打包源码（兼容特殊字符标签）
            git clone --depth 1 --branch "$tag_name" "https://github.com/$upstream_repo.git" "$workdir/$repo_name"
            pushd "$workdir/$repo_name" >/dev/null
            archive_name="${repo_name}-${tag_name//\//-}.zip"
            git archive --format=zip -o "../$archive_name" HEAD
            popd >/dev/null

            # 生成同步元数据
            timestamp=$(date -u +"%Y-%m-%d-%s")
            sync_tag="release-${timestamp}"
            md5_sum=$(md5sum "$workdir/$archive_name" | awk '{ print $1 }')

            # 创建 Release
            gh release create "$sync_tag" "$workdir/$archive_name" \
              --title "${timestamp}: ${repo_name} (${tag_name})" \
              --notes "MD5: ${md5_sum}\nRepo: ${upstream_repo}\nSource Tag: ${tag_name}"

            # 记录同步历史
            echo "$tag_name" > "$history_file"
          done

      - name: Commit sync history
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sync-history
          git commit -m "Update sync records" || exit 0
          git push
